name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Build application
      run: npm install
    - name: Run BackEnd
      run: npm run start-be &
    - name: Wait for backend
      run: sleep 5
    - name: Run FrontEnd
      run: npm run start-fe &
    - name: Wait for frontend
      run: sleep 5
    - name: Install playwright browsers
      run: npx playwright install
    - name: Run tests
      run: npm run test-ui